### PR TITLE
Issue #11 - fix full widthing of blocks (alt, loop, etc) instead bound to inner content

### LINKED ISSUE #11: Loop and Alt use the full width instead of only covering the leftmost to rightmost inner columns.
If I have 5 columns and a loop around 2 of them the outer box of the loop is the full width of the diagram. I expected it to only cover the leftmost to rightmost of the inner referenced columns. For a diagram with many loops it makes it visually very noisy when all boxes are full width.

```
One->Two:

loop: loop1
  Two->Three:
end

Three->Four:
Four->Five:
```

In the above code I would expect the loop to only encompass Two and Three. Instead it is the full width...

Screenshot 2020-10-08 at 17 28 14

(Although I'm queueing up a bunch of issues I may take a look at them myself - I just wanted to be able to track and prioritise them)

### PR DESCRIPTION
**Pull request by TheMightyGit**
Fixes #11 

**Q: Should I check in the `tests/testout.html` file as part of the PR?**
**Q: Perhaps it should be flagged behind a `--condensed-blocks` flag?**

Currently any diagram with several blocks and >5 columns becomes hard to eye parse...

Screenshot 2020-10-08 at 22 03 26

...this PR bounds blocks to the inner (including nested) content...

Screenshot 2020-10-08 at 22 55 31

```
participant One
participant Two
participant Three
participant Four
participant Five
participant Six
participant Seven
participant Eight
participant Nine
participant Ten

One->Two:

loop: loop1
  Two->Three:
  note over Three: woof
  loop: loop2
    Three->Four:
  end
end

Four->Five:

loop: loop3
  alt: xxx
    Six->Eight: oof
  elsealt: yyy
    Six->Nine: oof
  end
end
```

### Tests no longer fails (got a div by zero for a while there)

```
$ ./runtests.sh
Test: humanActorStyles.seq
Test: humanActors.seq
Test: humanActors2.seq
Test: offsideActors1.seq
Test: offsideActors2.seq
Test: offsideActors3.seq
Test: offsideActors4.seq
Test: optblock.seq
Test: test1.seq
Test: test2.seq
Test: test3.seq
Test: test4.seq
Test: test5.seq
Test: test6.seq
Test: test7.seq
Test: testComments.seq
Test: testConcurrent.seq
Test: testDeepNesting.seq
Test: testDividers.seq
Test: testDividersNoText.seq
Test: testIf.seq
Test: testIfElse.seq
Test: testIfSelf.seq
Test: testLargeObjectNames.seq
Test: testLoop.seq
Test: testMultiNotes.seq
Test: testMultiNotes2.seq
Test: testNestedIf.seq
Test: testNoActors.seq
Test: testNoBottomActors.seq
Test: testSelfArrows.seq
Test: testSelfArrows2.seq
Test: testSmallTitle.seq
Test: testStyles.seq
```

#### But the following look weird... (all (?) fixed now)

FIXED: Blocks don't align (sibling blocks are not taken into account) and the bottom dotted line is missing from the first block...

Screenshot 2020-10-08 at 22 30 51

Screenshot 2020-10-08 at 22 48 37

FIXED: Well this just looks plain odd... but I think it's another case of sibling block sizes not being taken into account...

Screenshot 2020-10-08 at 22 33 51

Screenshot 2020-10-08 at 22 48 52

### CODE REVIEW

**Comment by lmika** [comment]
Hi @TheMightyGit ,

Thank you very much for your PR.  I really appreciate it that you've taken the time to take a look at this.  I'm just going through the code now.  It's been a few years since I've last looked at this so it might take some time for me to get up to speed.

> Should I check in the tests/testout.html file as part of the PR?

I think this file is actually being tracked so it should be OK to check it in.  If you'd like to go above and beyond, it might be best if this file was actually removed and added to `.gitignore`, but don't feel obliged to do so.

> Perhaps it should be flagged behind a --condensed-blocks flag?

In general I prefer options that modify the attributes of the diagram to be declared in some way in the diagram itself.  That way, the diagram can be recreated without having to remember any additional switches that need to be enabled.  When I was working on this, I had the idea of adding directives to modify attributes of the diagram, like `set option = bla`, but I've never got round to doing that.  I guess down this line this could be a style attribute, like:

```
style alt (
    condense-blocks=true
)
```

For now, I'm happy for this to be left enabled, or maybe feature flagged with a constant.

Thanks,

Leon

File: seqdiagram/graphicbuilder.go [hunk 1]
```diff
@@ -231,17 +232,61 @@ func (gb *graphicBuilder) putBlockSegmentsConcurrently(row *int, depth int, acti
 	*row++
 }
 
+func getInnerRanksRecursive(subItems []SequenceItem) []int {
+	ranks := []int{}
+	for _, subItem := range subItems {
+		if action, isAction := subItem.(*Action); isAction {
+			ranks = append(ranks, action.From.rank)
+			ranks = append(ranks, action.To.rank)
```
Comment (lmika) [inline seqdiagram/graphicbuilder.go]: You may need to consider the case where the rank of `action.From` and `action.To` are the same.  These are for self referencing actions: e.g. `A->A: do this to self`.  In that case, the block region should probably span from the "from" rank to the "to" rank + 1.

Have a look at the output of _ testIfSelf.seq_ and you'll see that the region doesn't include the self referencing action.  There should be hidden ranks bordering the diagram so adding a rank to this should work.

**Review by lmika — APPROVED** [review]

File: seqdiagram/graphicbuilder.go [hunk 2]
```diff
@@ -231,17 +232,69 @@ func (gb *graphicBuilder) putBlockSegmentsConcurrently(row *int, depth int, acti
 	*row++
 }
 
+func getInnerRanksRecursive(subItems []SequenceItem) []int {
+	ranks := []int{}
+	for _, subItem := range subItems {
+		if action, isAction := subItem.(*Action); isAction {
+			ranks = append(ranks, action.From.rank, action.To.rank)
```
Comment (lmika) [inline seqdiagram/graphicbuilder.go:239]: Sorry, but you might need to take another look at this if the "from" rank is the same as the "to" rank.  Maybe replace this line with the following code snippet:

```go
			if action.From.rank == action.To.rank {
				ranks = append(ranks, action.From.rank, action.To.rank + 1)
			} else {
				ranks = append(ranks, action.From.rank, action.To.rank)
			}
```

Try running the tests before and after making this change and comparing the diagram generated for the "testIfSelf.seq" test case.

**Review by lmika — APPROVED** [review]

**Comment by lmika** [comment]
Hi @TheMightyGit , I finally got round to merging this.  So sorry it took so long.

Thanks for your contribution.
